### ISSUE TITLE
Activity 1: Your First Caption

### ISSUE THREAD

**Issue by ncsokas** [github-developer-training-school/nice-training#2]
Using the API, I have just created a file with a random octocat for you to caption. In this activity, we will learn how to make changes to files in our GitHub repository.

- [ ] @AkshayJagtapNice
- [ ] @LiorEpshtein
- [ ] @OmerDek
- [ ] @ShayRachmani
- [ ] @adarshnairnice1997
- [ ] @ilanhaz
- [ ] @jayeshsapariyanice
- [ ] @kdoke-nice
- [ ] @narsharma
- [ ] @ncsokas
- [ ] @onkulkarni
- [ ] @talisht21
- [ ] @Vadim-Grinevich
- [ ] @sjadhwani

**Comment by yanalanova** [comment]
@yanalanova
